[project]
name = "backgammon-qlearning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "<3.13,>=3.12"
dependencies = [
    "gymnasium>=1.1.1",
    "numpy>=2.1.3",
    "tensorflow>=2.19.0",
    "tqdm>=4.67.1",
]
